theme: jekyll-theme-cayman
title: Welcome to the new software Design inspired video game.
description: Feel free to read about our project and explore the creation of two software design students making a game that simulates the software design experience for their software design final project.
